### ISSUE TITLE
What is server_main? and other Questions

### ISSUE THREAD

**Issue by D4RKH0R1Z0N** [MrJaysa/python-rdp#1]
What is server_main and does it require any dependencies? in python? and does it support python3 can I run pyinstaller to convert it to a exe file?

**Comment by MrJaysa** [comment]
The server_main is a socketio python server written with flask, it acts as the server for the connection of the client and the device. it's still under development, but I think it can be compile with pyinstaller to create an executable

**Comment by MrJaysa** [comment]
> What is server_main and does it require any dependencies? in python? and does it support python3 can I run pyinstaller to convert it to a exe file?

The server_main is a socketio python server written with flask, it acts as the server for the connection of the client and the device. it's still under development, but I think it can be compile with pyinstaller to create an executable
